sustainable-computing-io/kepler-helm-chart

.github/workflows/integration_test.yml, .helmignore, templates/server.yaml
switch CI to customer Action for cluster creation.
add helm lint.
Signed-off-by: Sam Yuan <yy19902439@126.com>
=> CI: switch CI to customer Action

Chart.yaml, templates/server.yaml, values.yaml
Hi,
this PR allows to configure `kepler` using environment variables.
Thanks
=> configure kepler using env var

chart/kepler/Chart.yaml, chart/kepler/templates/server.yaml, chart/kepler/values.yaml
Hi,
I would like to use the `appVersion` field as first choice for the container image tag.
Thanks
=> Use appVersion as image.tag

chart/kepler/Chart.yaml, chart/kepler/templates/daemonset.yaml, chart/kepler/values.yaml
Hi,
this PR adds to option to add custom `annotations` to the `DaemonSet`.
Thanks
=> Allow set `DaemonSet` annotations

chart/kepler/Chart.yaml
Update to just released `release-0.5`
=> kepler(0.4.0): appVersion `release-0.5`

chart/kepler/Chart.yaml, chart/kepler/templates/daemonset.yaml, chart/kepler/templates/rolebinding.yaml
=> keplet(0.4.2): allow cluster role to watch pods

chart/kepler/Chart.yaml
=> kepler(0.4.3): bump to release-0.5.1

.github/workflows/integration_test.yml
ci: bump kepler action version to v0.0.1
=> ci: bump kepler action version to v0.0.1

chart/kepler/Chart.yaml, chart/kepler/templates/servicemonitor.yaml
When attempting to deploy the [`kepler-helm-chart`](https://github.com/sustainable-computing-io/kepler-helm-chart/tree/main) with an enabled `ServiceMonitor` and when specifying a custom namespace, the following error occurs:
```bash
Error: INSTALLATION FAILED: YAML parse error on kepler/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context
```
``` yaml
serviceMonitor:
enabled: true
namespace: prometheus
```
Installing the helm chart with the `custom-values.yaml` file:
```bash
helm install kepler-chart kepler/kepler --values custom-values.yaml --namespace kepler
```
This generates the aforementioned error:
```bash
Error: INSTALLATION FAILED: YAML parse error on kepler/templates/servicemonitor.yaml: error converting YAML …
```
=> Fix mapping value error

chart/kepler/Chart.yaml
=> kepler(0.5.1): bump to release-0.5.5

chart/kepler/Chart.yaml, chart/kepler/values.yaml
=> kepler(0.5.4): bump to release-0.7.2

.github/workflows/integration_test.yml, chart/kepler/Chart.yaml
=> kepler(0.5.6): bump to release-0.7.8

chart/kepler/Chart.yaml
=> kepler(0.5.8): bump to release-0.7.11

chart/kepler/Chart.yaml, chart/kepler/templates/daemonset.yaml, chart/kepler/templates/rolebinding.yaml, chart/kepler/templates/service.yaml
Closes: https://github.com/sustainable-computing-io/kepler-helm-chart/issues/67
=> Use fullname instead of name to name resource

.github/dependabot.yml, .github/workflows/integration_test.yml
add dep bot for GHA and update pipeline
=> [fix]: add dep bot for GHA and update pipeline

.github/workflows/integration_test.yml
address https://github.com/sustainable-computing-io/local-dev-cluster/issues/103
=> Try to fix ci

chart/kepler/Chart.yaml
=> kepler(0.5.14): bump to release-0.8.0

chart/kepler/Chart.yaml, chart/kepler/templates/daemonset.yaml
This resolves https://github.com/sustainable-computing-io/kepler-helm-chart/issues/83
=> helm: Add readinessProbe to daemonSet

chart/kepler/Chart.yaml, chart/kepler/templates/networkpolicy.yaml, chart/kepler/values.yaml
This adds an optional NetworkPolicy you can use to limit the traffic of the kepler container.
=> helm: Add optional networkPolicy

chart/kepler/Chart.yaml, chart/kepler/templates/daemonset.yaml
Fix [issue #81](https://github.com/sustainable-computing-io/kepler-helm-chart/issues/81)
=> fix(): mount config dir to support readonlyfilesystem
